Making everything up to date!
mastercomfig/hud-db pull request #106
Opened 2023-06-25 23:20 UTC by hexereii

Added in new banner/links/descriptions/etc!

2023-06-25 23:33 UTC, rbjaxter requested changes

2023-06-25 23:33 UTC, rbjaxter commented on hud-data/berryhud.json
> +  "resources":
missing opening [ after `"resources":`

that line should be `"resources": [`

2023-06-25 23:33 UTC, rbjaxter commented on hud-data/berryhud.json
> +	]
you can delete these lines, and then remove the comma after the bracket on line 38

2023-06-25 23:33 UTC, rbjaxter commented on hud-data/berryhud.json
> +  ]
this one's missing a comma after the bracket

2023-06-25 23:33 UTC, rbjaxter commented on hud-data/berryhud.json
> +    "steam_group": "",
I believe @mastercoms prefers empty lines like this to just be deleted, so you can just remove line 6

2023-06-25 23:33 UTC, rbjaxter commented on hud-data/berryhud.json
> +  "ultiduo"],
just for formatting, you'll want to move the `],` down to its own line

2023-06-25 23:33 UTC, rbjaxter commented on hud-data/berryhud.json
> +    "cool-image-1"
you'll want to remove this line

2023-06-26 00:08 UTC, rbjaxter commented on hud-data/berryhud.json
> +  "verified": true
you can remove these two lines. I believe `prelease` defaults to false, and `verified` is an internal hud-db thing you don't want to have

2023-06-26 00:14 UTC, rbjaxter commented
@mastercoms other than that last review, I believe everything looks good otherwise. You should probably still take a peep though just in case I missed something, since there were a handful of corrections that needed to be made from the initial commit

2023-06-26 00:46 UTC, mastercoms requested changes

2023-06-26 00:46 UTC, mastercoms commented on hud-data/berryhud.json
> +    "berrybanner.png"
Remove .png

2023-06-27 03:25 UTC, rbjaxter approved these changes

2023-06-27 04:36 UTC, mastercoms approved these changes

2023-06-27 04:36 UTC, merged