add bania hud
mastercomfig/hud-db pull request #296
Opened 2024-05-20 19:30 UTC by HUBM3N

https://imgur.com/a/ULn1arh

2024-05-22 00:19 UTC, rbjaxter requested changes

2024-05-22 00:19 UTC, rbjaxter commented on hud-data/bania-hud.json
> +  "": "a hud i made lolololol",
```suggestion
```

2024-05-22 00:19 UTC, rbjaxter commented on hud-data/bania-hud.json
> +  "resources": [
`resources` is meant to list the names of the images you'd have in `hud-resources/bania-hud`:
<img width="578" alt="chrome_KJ0vaR7y7y" src="https://github.com/mastercomfig/hud-db/assets/509599/b42b77b6-9580-405a-b8d2-8f1d24f18dff">

2024-05-22 00:19 UTC, rbjaxter commented on hud-data/bania-hud.json
> +    "notepad++"
```suggestion
    "bania-hud-banner"
```

2024-05-22 00:19 UTC, rbjaxter commented on hud-data/bania-hud.json
> +    ""
```suggestion
    "black and white"
```

2024-05-22 00:19 UTC, rbjaxter commented on hud-data/bania-hud.json
> +      "English"
```suggestion
      "en"
```
you use the [ISO 639-1](https://en.wikipedia.org/wiki/List_of_ISO_639_language_codes) codes for these (presumably at least, even though tf2 has a few other ones used i think)

just change it to en

2024-05-22 00:19 UTC, rbjaxter commented on hud-data/bania-hud.json
> +    ]
```suggestion
```

this now becomes a duplicate once the other one is corrected

2024-05-22 00:19 UTC, rbjaxter commented on hud-pages/bania-hud.md
This is a markdown (.md) file, so you use the markdown language: https://www.markdownguide.org/basic-syntax/

2024-05-22 00:19 UTC, rbjaxter commented on hud-pages/bania-hud.md
> +<https://github.com/HUBM3N/Bania-Hud>
```suggestion
https://github.com/HUBM3N/Bania-Hud  

```

2024-05-22 00:19 UTC, rbjaxter commented on hud-pages/bania-hud.md
> +<https://gamebanana.com/mods/514784>
```suggestion
https://gamebanana.com/mods/514784  

```

2024-05-22 00:19 UTC, rbjaxter commented on hud-pages/bania-hud.md
> +<https://github.com/HUBM3N/Bania-Hud>
```suggestion
https://github.com/HUBM3N/Bania-Hud  

```

2024-05-22 00:19 UTC, rbjaxter commented on hud-pages/bania-hud.md
> +<https://steamcommunity.com/profiles/76561198992606708>
```suggestion
https://steamcommunity.com/profiles/76561198992606708

```

2024-06-10 20:28 UTC, mastercoms submitted a review, later dismissed

2024-06-10 20:32 UTC, mastercoms approved these changes

2024-06-10 20:32 UTC, merged