add optivex hud
mastercomfig/hud-db pull request #321
Opened 2024-06-18 16:03 UTC by tekunotri

adding a slightly cleaned up optive hud with permission given by the creator: https://i.imgur.com/gefweJQ.png

2024-06-18 16:33 UTC, rbjaxter requested changes

2024-06-18 16:33 UTC, rbjaxter commented on hud-data/optive-hud.json
> +      "optivehud-menu https://youtu.be/DmAiJ9Oz-nY?si=9I9GbAkCXs4Y_yrx"
```suggestion
      "optivehud-menu",
      "https://youtu.be/DmAiJ9Oz-nY?si=9I9GbAkCXs4Y_yrx"
```

2024-06-18 19:29 UTC, tekunotri commented on hud-data/optive-hud.json
> +      "optivehud-menu https://youtu.be/DmAiJ9Oz-nY?si=9I9GbAkCXs4Y_yrx"
whoops. fixed

2024-06-19 03:26 UTC, rbjaxter approved these changes

2024-06-19 03:26 UTC, merged