ahud-cc - Scream Fortress 2024 update
mastercomfig/hud-db pull request #428
Opened 2024-12-02 22:41 UTC by jakadak

2024-12-09 15:26 UTC, CriticalFlaw approved these changes

2024-12-10 18:47 UTC, rbjaxter requested changes

2024-12-10 18:47 UTC, rbjaxter commented on hud-pages/ahud-cc.md
>  ---
```suggestion
# Have a lovely day, au revoir!
```

If I'm understanding the error correctly, this is what it wants you to do instead.

2024-12-14 22:05 UTC, rbjaxter approved these changes

2024-12-14 22:05 UTC, merged