SpaceHUD page additions
mastercomfig/hud-db pull request #48
Opened 2023-02-05 17:01 UTC by BingBongBonky

2023-02-05 22:07 UTC, rbjaxter requested changes
just one small change, everything looks good though as far as I can tell :D

2023-02-05 22:07 UTC, rbjaxter commented on hud-data/spacehud.json
> +    "spacehud-01-mainpage"
I believe you need a comma after `"spacehud-01-mainpage"` since you're adding a new resource below it

2023-02-05 23:38 UTC, BingBongBonky commented
Oops! Fixed now

2023-02-06 00:12 UTC, rbjaxter approved these changes

2023-02-06 01:15 UTC, merged