Updated Hypnotize's HUDs
mastercomfig/hud-db pull request #91
Opened 2023-05-08 19:23 UTC by Hypnootize

2023-05-08 20:32 UTC, mastercoms requested changes

2023-05-08 20:32 UTC, mastercoms commented on hud-resources/lighthud/lighthud-banner.png
LIGHT HUD?

2023-05-08 21:22 UTC, Hypnootize commented on hud-resources/lighthud/lighthud-banner.png
Whoops, I somehow managed to not see that LOL. Thanks for noticing, should be good now!

2023-05-15 20:44 UTC, rbjaxter approved these changes

2023-05-15 22:03 UTC, mastercoms approved these changes

2023-05-15 22:03 UTC, merged